### ISSUE TITLE
Group Update via M2M fails with Error

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/groups-api#23]
Group Update operation with a M2M token fails with an error "Neo.ClientError.Statement.ParameterMissing". 

The updateBy parameter is not set when a M2M token is used
https://github.com/topcoder-platform/groups-api/blob/develop/src/services/GroupService.js#L212
<img width="846" alt="UpdatedBy" src="https://user-images.githubusercontent.com/5771673/67070924-ea53d480-f19e-11e9-9c83-2c86daddf3b1.png">

**Comment by cwdcwd** [comment]
looks like this one was resolve [here](https://github.com/topcoder-platform/groups-api/blob/develop/src/services/GroupService.js#L205)
