### ISSUE TITLE
Selecting Private Group option during Group creation throws error

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/groups-api#25]
Creating a private group throws an "Internal Server Error".
<img width="377" alt="InternalError" src="https://user-images.githubusercontent.com/5771673/67278950-ad157c80-f4e7-11e9-9dce-6bd330388cc1.png">

Input JSON
{"param":{"name":"ABC","privateGroup":true,"selfRegister":false}}

**Comment by cwdcwd** [comment]
this looks resolved

**Comment by cwdcwd** [comment]
Error reproducible when no `description` field is present

**Comment by sharathkumaranbu** [comment]
Based on the discussion with @dushyantb, fix has been made in the Admin application. Issue is with the Client and not at the Server.

**Comment by bountyC0d3r** [comment]
made description field mandatory in admin-app; hence closing this issue
