### ISSUE TITLE
Unable to add Child Group as member to Parent Group 

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/groups-api#63]
-- Member addition to Groups doesnt work when Member is a group.
-- This functionality works in Production but not in Dev Environment.

@wdprice pls verify for Impact on Skill Search App deployment.

**Comment by wdprice** [comment]
@lakshmiathreya - this does not affect skill search app.

However, if this issue affects existing production applications I would consider this a blocker to deployment.

**Comment by lakshmiathreya** [comment]
https://drive.google.com/file/d/1Ih6W8K-WIruQL38sBojPmfM_9EE8orNz/view?usp=sharing

**Comment by lakshmiathreya** [comment]
@wdprice - we might have to discuss with @ajefts to assess Impact on Production ...

**Comment by wdprice** [comment]
@dushyantb - can you investigate this? We will not be able to migrate Groups to prod while this issue exists.

CC: @cwdcwd

**Comment by bountyC0d3r** [comment]
@wdprice this has been fixed and deployed on `dev`

**Comment by wdprice** [comment]
@lakshmiathreya - ready for re-test

**Comment by lakshmiathreya** [comment]
<img width="1253" alt="Screenshot 2020-08-13 at 6 18 07 PM" src="https://user-images.githubusercontent.com/51733042/90136181-656f2280-dd91-11ea-82d9-db72635917a5.png">
