### ISSUE TITLE
Groups Search & Swagger Updates

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/groups-api#73]
Based on this thread:
https://github.com/topcoder-platform/work-manager/issues/899#issuecomment-730435005

We need to:

- [ ] add fuzzy search by name to allow for dropdown auto-completion. 
- [ ] Make sure the swagger is up to date.
- [ ] Make sure the swagger is hosted in the deployed API like https://api.topcoder.com/v5/challenges/docs

**Comment by rootelement** [comment]
Test case - right now, this: api.topcoder.com/v5/groups?name=Test returns no results. But the first result with no filter returns:
```json
{
        "ssoId": "",
        "updatedBy": "23225544",
        "description": "Test-CWD",
        "privateGroup": true,
        "oldId": "1",
        "organizationId": "",
        "createdAt": "2017-05-29T13:54:47.000Z",
        "selfRegister": false,
        "createdBy": "40278876",
        "domain": "",
        "name": "Test - Changed-CWD",
        "id": "4061f24e-96f5-4b46-8c53-fe63f91f3775",
        "updatedAt": "2020-08-14T16:31:13.667Z",
        "status": "active"
    }
```

You should be able to search for Test and get that result returned.

**Comment by lakshmiathreya** [comment]
@rootelement - is the fix done - would help if you could add current status in the Label? ...

**Comment by rootelement** [comment]
Is _this_ fix done? it was opened 2 hours before your post.... Mithun isn't _that_ fast. He's gotta run a task or challenge to get this implemented. He will update with status here when in flight and when completed. @callmekatootie please keep @lakshmiathreya updated.

**Comment by callmekatootie** [comment]
@rootelement @lakshmiathreya The changes are in dev. Let me know if I am good to push to prod

**Comment by lakshmiathreya** [comment]
@callmekatootie I will let you know once my tests are done in Dev ...
