### ISSUE TITLE
Old id missing in Groups listing response

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/groups-api#81]
Old id is returned in Prod and missing in Dev - 
<img width="1680" alt="Screenshot 2020-12-02 at 6 49 38 PM" src="https://user-images.githubusercontent.com/51733042/100878055-ad948b00-34cf-11eb-954d-e077c27b2506.png">

<img width="1680" alt="Screenshot 2020-12-02 at 6 43 06 PM" src="https://user-images.githubusercontent.com/51733042/100878033-a66d7d00-34cf-11eb-8562-d357c61278bd.png">

**Comment by lakshmiathreya** [comment]
cc @rootelement

**Comment by callmekatootie** [comment]
@lakshmiathreya Do you happen to know how these groups were created - I just created one and I see the oldId:

```json
{
    "organizationId": "36ed815b-3da1-49f1-a043-aaed0a4e81ad",
    "ssoId": "",
    "createdAt": "2020-12-06T17:03:11.843Z",
    "selfRegister": false,
    "createdBy": "8547899",
    "domain": "topcoder",
    "name": "Testing mithun old id creation",
    "description": "test mithun",
    "privateGroup": true,
    "id": "abaf2685-8c9f-443c-adbf-f4d4c9acdc57",
    "oldId": "20000904",
    "status": "active"
}
```

I tried multiple times and I could not get a group without old id...

Probably the processor was down when the group was created? Not sure how to resolve this. Will check with James...
