### ISSUE TITLE
Need to implement an option on "/v5/groups" that returns all parent groups as well as groups the user is in

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/groups-api#84]
The most used call in groups API is plan old "/v5//groups/:groupId". This is because challenge-api needs to determine:

Step 1:  Get all the groups the user directly belongs to (which is often > 1000).
Step 2: For each of those groups, get all the parent groups of that group
Step 3: Combine all these group IDs together

Step 2 makes a separate call for every group returned from Step 1, so a single call to challenge-api often results in over 1,000 calls to groups api:

3 Hour chart

![image](https://user-images.githubusercontent.com/7715262/114813245-53f27600-9d77-11eb-8fcc-f68aed806fac.png)

2.3 Million calls to groups API in 3 hours due to this (this is typical across any 3 hours).

In challenge-api this process begins here: https://github.com/topcoder-platform/challenge-api/blob/1249f141c194229386f6bcf694fda138a9ca82ae/src/services/ChallengeService.js#L400

You can inspect the logic of exactly what it's doing by following `helper.getCompleteUserGroupTreeIds`

The suggested solution here is to implement a param such as `/v5/groups?includeParentGroups=true` which implements this logic so that it can be removed from challenge-api and handled in groups-api (via neo4j directly).

**Comment by bountyC0d3r** [comment]
this has been covered as a part of the `groupeligibilitycheck` end point

**Comment by lakshmiathreya** [comment]
cc @SathyaJayabal pls verify this and update QA status.

**Comment by SathyaJayabal** [comment]
@dushyantb , the `groupeligibilitycheck` endpoint only returns a check:true/false . How do we get the list of groups the user has access to (including parent groups) ?
Do we use the `groups/MemberGroups/{oldMemberId}`  endpoint instead? This returns the list of groups including the parent groups, but it returns only the list of old group ids. The challenge-api will need to make further calls to get additional data for each of those groups.

**Comment by rakibansary** [comment]
Groups micro-service already has an Api that returns all the groups accessible by a member. It has now been updated to return UUIDs which can be used by Challenge Api to reduce number of Api calls to get a members accessible groups in this commit https://github.com/topcoder-platform/groups-api/commit/d1ff0978f1411195e7283612007efa385d80b9d2

**Comment by SathyaJayabal** [comment]
verified on dev
using the uuid=true param
<img width="1440" alt="Screenshot 2022-03-21 at 10 56 23 AM" src="https://user-images.githubusercontent.com/58783823/159209336-09fda8c3-4d13-4602-85c2-91c2e4fc3aa5.png">
without the new param
<img width="1440" alt="Screenshot 2022-03-21 at 10 56 45 AM" src="https://user-images.githubusercontent.com/58783823/159209345-62f72988-0db2-4ea4-a6f1-974df5ef3203.png">

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PROD-933?focusedCommentId=17337
