### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/groups-api#97]
Issues have been repeatedly reported where the actual root cause is the performance of the Groups API and the overall architecture of how we manage groups.

A recent example of an issue that's the result of this is https://github.com/topcoder-platform/community-app/issues/5940

References:
- https://github.com/topcoder-platform/groups-api/issues/84
- https://github.com/topcoder-platform/groups-api/issues/64

We need to:
- Analyse the performance of the Groups API and find weak points
- Refactor the Groups API to improve performance

**Comment by lakshmiathreya** [comment]
cc @SathyaJayabal

**Comment by bountyC0d3r** [comment]
- group API is already optimised and performing well
